{
 "title": "MiniDLNA",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Active Clients",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(minidlna_clients) > 0" }
   ]
  },
  {
   "title": "Total Clients",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(minidlna_clients)" }
   ]
  },
  {
   "title": "Image files",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "minidlna_files{type=\"image_files\"}"
    }
   ]
  },
  {
   "title": "Audio files",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "minidlna_files{type=\"audio_files\"}"
    }
   ]
  },
  {
   "title": "Video files",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "minidlna_files{type=\"video_files\"}"
    }
   ]
  },
  {
   "title": "Files",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "minidlna_files", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Clients",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    { "expr": "minidlna_clients" }
   ]
  }
 ]
}